settings:
    contactInformation:
        en: "Your Contact Information"
        fr: "Vos informations de contact"
        la: "Notitia contactus tuum"

    renewals:
        comingSoon:
            en: "Online membership renewals coming soon"
            fr: "Renouvellements d'adhésion en ligne à venir"
            la: "Renovatio sodalitas veniet cito"

    title:
        en: "User settings for [<b>{{username}}</b>]"
        fr: "Profil de l'utilisateur [{{username}}]"
        la: "User settings for [<b>{{username}}</b>]"

    form: 
        firstname:
            en: "First Name"
            fr: "Prénom"
            la: "Praenomen"

        firstname.placeholder:
            en: "Your first name"
            fr: "Votre prénom"
            la: "Praenome tuum"

        lastname:
            en: "Last Name"
            fr: "Nom"
            la: "Cognomen"

        lastname.placeholder:
            en: "Your last name"
            fr: "Votre nom"
            la: "Cognomen tuum"

        button:
            en: "Save"
            fr: "Sauvegarder"
            la: "Servo"
    
    messages: 
        error: 
            fail:
                en: "<strong>An error has occurred!</strong> Settings could not be saved."
                fr: "<strong>Une erreur est survenue!</strong> Votre profil n'a pas été sauvegardé."
                la: "<strong>An error has occurred!</strong> Settings could not be saved."

            emailexists:
                en: "<strong>E-mail is already in use!</strong> Please choose another one."
                fr: "<strong>Cet E-mail est déjà utilisé!</strong> Veuillez en choisir un autre."
                la: "<strong>E-mail is already in use!</strong> Please choose another one."
        
        success:
            en: "<strong>Settings saved!</strong>"
            fr: "<strong>Votre profil a été sauvegardé!</strong>"
            la: "<strong>Settings saved!</strong>"

        validate: 
            firstname: 
                required:
                    en: "Your first name is required."
                    fr: "Votre prénom est requis."
                    la: "Your first name is required."

                minlength:
                    en: "Your first name is required to be at least 1 character"
                    fr: "Votre prénom doit comporter au moins un caractère"
                    la: "Your first name is required to be at least 1 character"

                maxlength:
                    en: "Your first name cannot be longer than 50 characters"
                    fr: "Votre prénom ne doit pas comporter plus de 50 caractères"
                    la: "Your first name cannot be longer than 50 characters"
            
            lastname: 
                required:
                    en: "Your last name is required."
                    fr: "Votre nom est requis."
                    la: "Your last name is required."

                minlength:
                    en: "Your last name is required to be at least 1 character"
                    fr: "Votre nom doit comporter au moins un caractère"
                    la: "Your last name is required to be at least 1 character"

                maxlength:
                    en: "Your last name cannot be longer than 50 characters"
                    fr: "Votre nom ne doit pas comporter plus de 50 caractères"
                    la: "Your last name cannot be longer than 50 characters"

